server:
  address: 0.0.0.0
  port: 8081

elasticsearch:
  host: ${ELASTICSEARCH_HOST:https://localhost:9200}
  username: ${ELASTICSEARCH_USERNAME:}
  password: ${ELASTICSEARCH_PASSWORD:}
  ssl:
    insecure: ${ELASTICSEARCH_SSL_INSECURE:true}
    # 운영은 직접 truststore를 경로 지정
    truststore-path: ${ELASTICSEARCH_SSL_TRUSTSTORE_PATH:}
    truststore-password: ${ELASTICSEARCH_SSL_TRUSTSTORE_PASSWORD:changeit}

kakao:
  api:
    key: ${KAKAO_API_KEY:}
